In [1]:
import os
import sys

module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

# FIX ME: Root dir as argument
root_dir = "../../data/picklerCheckpoints/"
is_compressed = True;

In [5]:
import numpy as np
import pandas as pd
import nbimporter
import geopandas as gpd
import commons.utility.pickle_util as pickle
import Preprocessing.DataEnrichment as de
import Preprocessing.SpatialMapping as sm
from shapely.geometry import Point

coord_system = {'init': 'epsg:4326'}

Importing Jupyter notebook from D:\Academics\MLRepoNew\ML2020-Uber-Data-Analysis\Preprocessing\SpatialMapping.ipynb

In [7]:
data = sm.run(['aug'])

Spatial join of all months found...Loading...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Loading file ../data/picklerCheckpoints/spatialJoinData/uber-spatial-data-14.p
Decompressing ../data/picklerCheckpoints/spatialJoinData/uber-spatial-data-14.p.pbz2..............Done
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

In [8]:
data

,Date/Time,Lat,Lon,Base,datetime,weatherCondition,humidity,pressure,temperature,windDirection,windSpeed,geometry,index_right,zone,LocationID,borough,borough_categ
0,4/1/2014 0:11:00,40.7690,-73.9549,B02512,04-01-2014:00,scattered clouds,40.0,1016.0,282.96,330.0,5.0,POINT (-73.95490 40.76900),42.0,Central Park,43.0,Manhattan,3.0
0,4/1/2014 0:11:00,40.7690,-73.9549,B02512,04-01-2014:00,scattered clouds,40.0,1016.0,282.96,330.0,5.0,POINT (-73.95490 40.76900),139.0,Lenox Hill East,140.0,Manhattan,3.0
0,4/1/2014 0:11:00,40.7690,-73.9549,B02512,04-01-2014:00,scattered clouds,40.0,1016.0,282.96,330.0,5.0,POINT (-73.95490 40.76900),140.0,Lenox Hill West,141.0,Manhattan,3.0
0,4/1/2014 0:11:00,40.7690,-73.9549,B02512,04-01-2014:00,scattered clouds,40.0,1016.0,282.96,330.0,5.0,POINT (-73.95490 40.76900),201.0,Roosevelt Island,202.0,Manhattan,3.0
2,4/1/2014 0:21:00,40.7316,-73.9873,B02512,04-01-2014:00,scattered clouds,40.0,1016.0,282.96,330.0,5.0,POINT (-73.98730 40.73160),78.0,East Village,79.0,Manhattan,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1028134,9/30/2014 22:58:00,40.7081,-74.0066,B02764,09-30-2014:22,broken clouds,72.0,1014.0,292.54,80.0,3.0,POINT (-74.00660 40.70810),86.0,Financial District North,87.0,Manhattan,3.0
1028134,9/30/2014 22:58:00,40.7081,-74.0066,B02764,09-30-2014:22,broken clouds,72.0,1014.0,292.54,80.0,3.0,POINT (-74.00660 40.70810),208.0,Seaport,209.0,Manhattan,3.0
1028135,9/30/2014 22:58:00,40.7140,-73.9496,B02764,09-30-2014:22,broken clouds,72.0,1014.0,292.54,80.0,3.0,POINT (-73.94960 40.71400),79.0,East Williamsburg,80.0,Brooklyn,1.0
1028135,9/30/2014 22:58:00,40.7140,-73.9496,B02764,09-30-2014:22,broken clouds,72.0,1014.0,292.54,80.0,3.0,POINT (-73.94960 40.71400),254.0,Williamsburg (North Side),255.0,Brooklyn,1.0
1028135,9/30/2014 22:58:00,40.7140,-73.9496,B02764,09-30-2014:22,broken clouds,72.0,1014.0,292.54,80.0,3.0,POINT (-73.94960 40.71400),255.0,Williamsburg (South Side),256.0,Brooklyn,1.0